version: '3.1'
services:
  mongo-servera:
    image: mongo:4.0.13-xenial
    restart: always
    volumes:
    - ./data-servera:/data/db
    - ./logs-servera:/var/log/mongodb/
    ports:
    - 27017:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root

  mongo-serverb:
    image: mongo:4.0.13-xenial
    restart: always
    volumes:
    - ./data-serverb:/data/db
    - ./logs-serverb:/var/log/mongodb/
    ports:
    - 27018:27017
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: root